# Use existing base image
FROM node:18-alpine

# Set working directory
WORKDIR /app

# Copy the package.json file
COPY package.json .

# Install application dependencies 
RUN npm install

# Copy the rest of application files
COPY . .

# Expose the port
EXPOSE 3000

# Run the application
CMD ["npm", "start"]