stages:
  - build
  - test

npm_build:
  stage: build
  script:
    - cd ./backend
    - npm install
    - cd ../frontend
    - npm install

docker_build:
  stage: build
  script:
    - cd ./backend
    - npm install
    - cd ../frontend
    - npm install
    - docker-compose up

backend_test:
  stage: test
  script:
    - cd ./backend
    - npm install
    - npm test

frontend_test:
  stage: test
  script:
    - cd ./frontend
    - npm install
    - npm test