image: node:14

stages:
  - build
  - run
  - test

backend_build:
  stage: build
  script:
    - cd ./backend
    - npm install

frontend_build:
  stage: build
  script:
    - cd ../frontend
    - npm install

backend_run:
  stage: run
  script:
    - cd ./backend
    - nodemon index.js

frontend_run:
  stage: run
  script:
    - cd ./frontend
    - npm start

backend_test:
  stage: test
  script:
    - cd ./backend
    - npm install
    - npm test

frontend_test:
  stage: test
  script:
    - cd ./frontend
    - npm install
    - npm test