image: node:14

stages:
  - run
  - test

backend:
  stage: run
  script:
    - cd ./backend
    - npm install
    - nodemon index.js

frontend:
  stage: run
  script:
    - cd ./frontend
    - npm install
    - npm start

backend_test:
  stage: test
  script:
    - cd ./backend
    - npm install
    - npm test

frontend_test:
  stage: test
  script:
    - cd ./frontend
    - npm install
    - npm test