version: "3.7"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: chatconnect-backend
    container_name: chatconnect-node-server
    ports:
      - "4040:4040"
    env_file: ./backend/.env
    environment:
      - NODE_ENV=development
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: chatconnect-frontend
    container_name: chatconnect-react-frontend
    ports:
      - "3000:3000"
