version: "3.7"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: chatconnect-backend
    container_name: chatconnect-node-server
    command: npm run start-docker
    volumes:
      - ./backend:/app/backend
      - /usr/src/app/node_modules
    ports:
      - "4040:4040"
    env_file: ./backend/.env
    environment:
      - NODE_ENV=development
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: chatconnect-frontend
    container_name: chatconnect-react-frontend
    command: npm start
    volumes:
      - ./frontend/src:/app/frontend/src
      - /usr/app/node_modules
    ports:
      - "3000:3000"
